const assert=require('node:assert/strict');
const fs=require('node:fs');
const i18n=fs.readFileSync('lib/i18n.ts','utf8');
const activity=fs.readFileSync('lib/activityTranslations.ts','utf8');
const edge=fs.readFileSync('supabase/functions/translate-activities/index.ts','utf8');
const me=fs.readFileSync('app/(tabs)/me.tsx','utf8');
const today=fs.readFileSync('app/(tabs)/today.tsx','utf8');
const plan=fs.readFileSync('app/(tabs)/plan.tsx','utf8');
const calendar=fs.readFileSync('app/(tabs)/calendar.tsx','utf8');
const widget=fs.readFileSync('widgets/android/TodayWidget.tsx','utf8');
const calWidget=fs.readFileSync('widgets/android/CalendarWidget.tsx','utf8');
const handler=fs.readFileSync('widget-task-handler.tsx','utf8');

assert.match(i18n,/type Language = 'it' \| 'en' \| 'fr' \| 'es'/);
assert.match(i18n,/let currentLanguage:Language='it'/);
assert.match(i18n,/LANGUAGES/);
assert.match(i18n,/flowos-language-v1/);
assert.match(i18n,/flowos-translate-activities-v1/);
assert.match(me,/Traduci anche le attività/);
assert.match(me,/I titoli originali vengono conservati/);
assert.match(activity,/flowos-original-titles-v1/);
assert.match(activity,/flowos-activity-translations-v1/);
assert.match(activity,/entry\.original===original/);
assert.match(edge,/Preserve meaning, names, acronyms, dates, numbers/);
assert.match(edge,/allowed=new Map/);
assert.match(today,/useActivityTitleMap/);
assert.match(plan,/useActivityTitleMap/);
assert.match(calendar,/useActivityTitleMap/);
assert.match(widget,/widgetStrings/);
assert.match(calWidget,/height: 'match_parent'/);
assert.match(handler,/getDisplayTitleMap/);

console.log('language and activity-translation regression tests passed');
