import { Platform } from 'react-native';
import * as WebBrowser from 'expo-web-browser';
import * as Linking from 'expo-linking';
import type { Session } from '@supabase/supabase-js';
import { recordDiagnostic } from './diagnostics';
import { supabase } from './supabase';
export const GOOGLE_SCOPES=['openid','email','profile','https://www.googleapis.com/auth/calendar.events','https://www.googleapis.com/auth/calendar.calendarlist.readonly','https://www.googleapis.com/auth/tasks'].join(' ');
export type GoogleSyncRange={startYear:number;endYear:number;labelStart:string;labelEnd:string;years:number[]};
export type GoogleCalendar={id:string;google_calendar_id:string;summary:string;description?:string|null;background_color?:string|null;foreground_color?:string|null;access_role:string;primary_calendar:boolean;selected:boolean;is_default:boolean};
export type GoogleTaskList={id:string;google_task_list_id:string;title:string;selected:boolean;is_default:boolean};
export type GoogleWorkspaceStatus={connection:null|{google_email?:string|null;last_sync_at?:string|null;last_sync_status:'pending'|'syncing'|'ok'|'error'|'disconnected';last_sync_error?:string|null;updated_at?:string|null};calendars:GoogleCalendar[];taskLists:GoogleTaskList[];range:GoogleSyncRange};
export type SyncProgress={percent:number;stage:string};
const SUPABASE_URL=process.env.EXPO_PUBLIC_SUPABASE_URL??'';const SUPABASE_KEY=process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'';const FUNCTION_URL=`${SUPABASE_URL}/functions/v1/google-workspace`;const GUARD_FUNCTION_URL=`${SUPABASE_URL}/functions/v1/google-sync-guard`;const REQUEST_TIMEOUT_MS=60000;const STALE_SYNC_THRESHOLD_MS=3*60*1000;const MAX_NETWORK_RETRIES=3;
function currentRange():GoogleSyncRange{const startYear=new Date().getFullYear(),endYear=startYear+1;return{startYear,endYear,labelStart:`01/01/${startYear}`,labelEnd:`31/12/${endYear}`,years:[startYear,endYear]};}
function errorMessage(error:unknown){return error instanceof Error?error.message:String(error||'Errore sconosciuto');}
function isTransientNetworkError(message:string){return /failed to fetch|network|send a request|timeout|tempo massimo|abort|unknownhost|unable to resolve host|dns|no address associated/i.test(message)||/\b(?:408|425|429|502|503|504|520|521|522|523|524)\b/.test(message);}
async function updateSyncFailure(message:string){const{data}=await supabase.auth.getUser();if(!data.user)return;const{error}=await supabase.from('google_connections').update({last_sync_status:'error',last_sync_error:message}).eq('user_id',data.user.id);if(error)recordDiagnostic('google-sync-mark-error-failed',error,'error');}
export async function recoverStaleGoogleSyncState(){const message='La precedente sincronizzazione è stata interrotta prima del completamento.';recordDiagnostic('google-sync-stale-state-recovered',{message},'warn');await updateSyncFailure(message);}
export function isSyncGenuinelyStale(connection:GoogleWorkspaceStatus['connection'],now:Date=new Date()){if(!connection||connection.last_sync_status!=='syncing')return false;if(!connection.updated_at)return true;return now.getTime()-new Date(connection.updated_at).getTime()>STALE_SYNC_THRESHOLD_MS;}
async function invoke(body:Record<string,unknown>,retries=MAX_NETWORK_RETRIES){const{data:sessionData,error:sessionError}=await supabase.auth.getSession();if(sessionError)throw sessionError;const accessToken=sessionData.session?.access_token;if(!accessToken)throw new Error('Sessione FlowOS scaduta. Esci e accedi nuovamente.');let lastError:unknown;let responseStatus:number|null=null;for(let attempt=0;attempt<=retries;attempt++){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);recordDiagnostic('google-function-request-start',{action:body.action,attempt:attempt+1});try{const response=await fetch(FUNCTION_URL,{method:'POST',signal:controller.signal,headers:{Authorization:`Bearer ${accessToken}`,apikey:SUPABASE_KEY,'Content-Type':'application/json','x-client-info':'flowos-google-sync/4.1'},body:JSON.stringify(body)});responseStatus=response.status;const raw=await response.text();let payload:any=null;try{payload=raw?JSON.parse(raw):null;}catch{payload=raw?{error:raw}:null;}recordDiagnostic('google-function-response',{action:body.action,status:response.status,ok:response.ok});if(!response.ok||payload?.error)throw new Error(String(payload?.error||`Google Workspace ha risposto con stato ${response.status}.`));return payload;}catch(error){lastError=error;const named=error as{name?:string};const message=named?.name==='AbortError'?'La richiesta di sincronizzazione ha superato il tempo massimo consentito.':errorMessage(error);const transient=(responseStatus!==null&&responseStatus>=500)||isTransientNetworkError(message);recordDiagnostic('google-function-request-failed',{action:body.action,attempt:attempt+1,message,transient},'error');if(attempt>=retries||!transient)break;const delay=1000*Math.pow(2,attempt);recordDiagnostic('google-function-retry-scheduled',{action:body.action,nextAttempt:attempt+2,delayMs:delay},'warn');await new Promise(resolve=>setTimeout(resolve,delay));}finally{clearTimeout(timeout);}}throw lastError instanceof Error?lastError:new Error(errorMessage(lastError));}
async function invokeSyncGuard(){const{data:sessionData,error:sessionError}=await supabase.auth.getSession();if(sessionError)throw sessionError;const accessToken=sessionData.session?.access_token;if(!accessToken)throw new Error('Sessione FlowOS scaduta. Esci e accedi nuovamente.');let lastError:unknown;let guardResponseStatus:number|null=null;for(let attempt=0;attempt<=MAX_NETWORK_RETRIES;attempt++){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);recordDiagnostic('google-sync-guard-request-start',{attempt:attempt+1});try{const response=await fetch(GUARD_FUNCTION_URL,{method:'POST',signal:controller.signal,headers:{Authorization:`Bearer ${accessToken}`,apikey:SUPABASE_KEY,'Content-Type':'application/json','x-client-info':'flowos-google-sync-guard/2.0'},body:JSON.stringify({action:'guard'})});guardResponseStatus=response.status;const raw=await response.text();let payload:any=null;try{payload=raw?JSON.parse(raw):null;}catch{payload=raw?{error:raw}:null;}recordDiagnostic('google-sync-guard-response',{status:response.status,ok:response.ok,error:payload?.error??null});if(!response.ok||payload?.error)throw new Error(String(payload?.error||`Google Sync Guard ha risposto con stato ${response.status}.`));recordDiagnostic('google-sync-guard-completed',payload??{});return payload;}catch(error){lastError=error;const named=error as{name?:string};const message=named?.name==='AbortError'?'Il controllo di sicurezza Google ha superato il tempo massimo consentito.':errorMessage(error);const transient=(guardResponseStatus!==null&&guardResponseStatus>=500)||isTransientNetworkError(message);recordDiagnostic('google-sync-guard-request-failed',{attempt:attempt+1,message,transient},'error');if(attempt>=MAX_NETWORK_RETRIES||!transient)break;await new Promise(resolve=>setTimeout(resolve,1000*Math.pow(2,attempt)));}finally{clearTimeout(timeout);}}throw new Error(`Controllo sincronizzazione Google fallito: ${errorMessage(lastError)}`);}
export async function signInWithGoogle(){const redirectTo=Platform.OS==='web'&&typeof window!=='undefined'?`${window.location.origin}/today`:'flowos://today';recordDiagnostic('google-oauth-started',{platform:Platform.OS,redirectTo});const{data,error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo,skipBrowserRedirect:Platform.OS!=='web',scopes:GOOGLE_SCOPES,queryParams:{access_type:'offline',prompt:'consent',include_granted_scopes:'true'}}});if(error)throw error;if(Platform.OS==='web')return data;if(!data?.url)throw new Error('Google non ha restituito un URL di accesso.');recordDiagnostic('google-oauth-browser-opening');try{const result=await WebBrowser.openBrowserAsync(data.url);recordDiagnostic('google-oauth-browser-opened',{resultType:result.type});}catch(error){recordDiagnostic('google-oauth-browser-open-failed',error,'error');await Linking.openURL(data.url);recordDiagnostic('google-oauth-system-browser-opened');}return data;}
let connectInFlight:Promise<unknown>|null=null;
export async function connectGoogleFromSession(session:Session,force=false){if(!session.provider_token)return null;if(connectInFlight){recordDiagnostic('google-connect-coalesced');return connectInFlight;}const marker=`flowos-google-connected-${session.user.id}-${session.provider_token.slice(-12)}`;if(!force&&Platform.OS==='web'&&typeof sessionStorage!=='undefined'&&sessionStorage.getItem(marker))return null;connectInFlight=invoke({action:'connect',providerToken:session.provider_token,providerRefreshToken:session.provider_refresh_token,scopes:GOOGLE_SCOPES,expiresIn:3600}).then(result=>{if(Platform.OS==='web'&&typeof sessionStorage!=='undefined')sessionStorage.setItem(marker,'1');return result;}).finally(()=>{connectInFlight=null;});return connectInFlight;}
export async function getGoogleWorkspaceStatus():Promise<GoogleWorkspaceStatus>{const result=await invoke({action:'status'},1);return{...result,range:currentRange()};}
const activeProgressListeners=new Set<(progress:SyncProgress)=>void>();let syncInFlight:Promise<{pushed:number;events:number;tasks:number;range?:GoogleSyncRange}>|null=null;
export function subscribeToSyncProgress(onProgress:(progress:SyncProgress)=>void){activeProgressListeners.add(onProgress);return()=>{activeProgressListeners.delete(onProgress);};}export function isGoogleSyncInFlight(){return syncInFlight!==null;}
export async function syncGoogleWorkspace(onProgress?: (progress:SyncProgress)=>void){if(onProgress)activeProgressListeners.add(onProgress);if(syncInFlight){recordDiagnostic('google-sync-coalesced-into-in-flight');try{return await syncInFlight;}finally{if(onProgress)activeProgressListeners.delete(onProgress);}}const broadcast=(progress:SyncProgress)=>activeProgressListeners.forEach(listener=>listener(progress));syncInFlight=syncGoogleWorkspaceInternal(broadcast);try{return await syncInFlight;}finally{syncInFlight=null;if(onProgress)activeProgressListeners.delete(onProgress);}}
async function syncGoogleWorkspaceInternal(onProgress?:(progress:SyncProgress)=>void){recordDiagnostic('google-sync-started');const totals={pushed:0,events:0,tasks:0};const range=currentRange();try{const plan=await invoke({action:'sync-start'});const calendars=plan.calendars??[],taskLists=plan.taskLists??[],years=range.years;const baseUnits=2+calendars.length*years.length+taskLists.length;let completed=0;const report=(stage:string,forced?:number)=>{const percent=forced??Math.min(98,Math.max(1,Math.round(completed/Math.max(1,baseUnits)*94)+3));onProgress?.({percent,stage});recordDiagnostic('google-sync-progress',{percent,stage});};report('Preparazione della sincronizzazione',3);await invokeSyncGuard();const pushed=await invoke({action:'sync-push'});totals.pushed=pushed.pushed??0;completed++;report('Modifiche FlowOS inviate a Google');for(const calendar of calendars){for(const year of years){let pageToken:string|null=null;do{const page=await invoke({action:'sync-calendar-page',calendarId:calendar.google_calendar_id,year,pageToken});totals.events+=page.imported??0;pageToken=page.nextPageToken??null;report(`Calendario ${calendar.summary}: anno ${year}`);}while(pageToken);completed++;report(`Calendario ${calendar.summary}: anno ${year} completato`);}}for(const list of taskLists){let pageToken:string|null=null;do{const page=await invoke({action:'sync-task-page',listId:list.google_task_list_id,pageToken});totals.tasks+=page.imported??0;pageToken=page.nextPageToken??null;report(`Google Tasks: ${list.title}`);}while(pageToken);completed++;report(`Google Tasks: ${list.title} completata`);}onProgress?.({percent:97,stage:'Finalizzazione della sincronizzazione'});await invoke({action:'sync-finish'});onProgress?.({percent:100,stage:'Sincronizzazione completata'});recordDiagnostic('google-sync-succeeded',totals);return{...totals,range};}catch(error){const message=errorMessage(error);const transient=isTransientNetworkError(message);if(transient){recordDiagnostic('google-sync-network-failure-kept-pending',{message},'warn');}else{try{await invoke({action:'sync-fail',message},0);}catch(markError){recordDiagnostic('google-sync-server-mark-error-failed',markError,'error');}await updateSyncFailure(message);}recordDiagnostic('google-sync-failed',{message,transient},'error');throw new Error(transient?'Sincronizzazione interrotta temporaneamente per un problema di rete. Le modifiche restano in sospeso e verranno ritentate.':message);}}
export async function disconnectGoogleWorkspace(){return invoke({action:'disconnect'});}export async function setSyncRange(startDate:string|null,endDate:string|null){return invoke({action:'set-sync-range',startDate,endDate});}export function friendlyCalendarName(name:string,ownEmail?:string|null){return ownEmail&&name.trim().toLowerCase()===ownEmail.trim().toLowerCase()?'Alex':name;}export async function setDefaultCalendar(id:string){const{error}=await supabase.rpc('set_default_google_calendar',{p_calendar_id:id});if(error)throw error;}export async function setDefaultTaskList(id:string){const{error}=await supabase.rpc('set_default_google_task_list',{p_task_list_id:id});if(error)throw error;}export async function setCalendarSelected(id:string,selected:boolean){const{error}=await supabase.from('google_calendars').update({selected}).eq('id',id);if(error)throw error;}export async function setTaskListSelected(id:string,selected:boolean){const{error}=await supabase.from('google_task_lists').update({selected}).eq('id',id);if(error)throw error;}