import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.57.4";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const url=Deno.env.get("SUPABASE_URL")!;
const serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const clientId=Deno.env.get("GOOGLE_CLIENT_ID")??"";
const clientSecret=Deno.env.get("GOOGLE_CLIENT_SECRET")??"";
const admin=createClient(url,serviceKey,{auth:{persistSession:false}});

async function userFromRequest(req:Request){const jwt=(req.headers.get("Authorization")??"").replace(/^Bearer\s+/i,"");const {data,error}=await admin.auth.getUser(jwt);if(error||!data.user)throw new Error("Sessione non valida");return data.user;}
async function accessToken(userId:string){const {data,error}=await admin.schema("private").from("google_oauth_tokens").select("*").eq("user_id",userId).maybeSingle();if(error||!data)throw new Error("Account Google non collegato");if(!data.expires_at||new Date(data.expires_at).getTime()>Date.now()+60000)return data.access_token as string;if(!data.refresh_token||!clientId||!clientSecret)throw new Error("Autorizzazione Google scaduta: accedi nuovamente");const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,refresh_token:data.refresh_token,grant_type:"refresh_token"})});const payload:any=await response.json();if(!response.ok||!payload.access_token)throw new Error(payload.error_description??payload.error??"Aggiornamento token non riuscito");await admin.schema("private").from("google_oauth_tokens").update({access_token:payload.access_token,expires_at:new Date(Date.now()+(payload.expires_in??3600)*1000).toISOString(),updated_at:new Date().toISOString()}).eq("user_id",userId);return payload.access_token as string;}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const user=await userFromRequest(req);const {commitmentId}=await req.json();if(!commitmentId)return json({error:"commitmentId mancante"},400);const {data:item,error}=await admin.from("commitments").select("*").eq("id",commitmentId).eq("user_id",user.id).maybeSingle();if(error||!item)return json({error:"Elemento non trovato"},404);if(!item.external_id){await admin.from("commitments").delete().eq("id",item.id).eq("user_id",user.id);return json({ok:true,googleDeleted:false});}const token=await accessToken(user.id);const endpoint=item.external_resource_type==="calendar_event"?`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(item.google_calendar_id)}/events/${encodeURIComponent(item.external_id)}`:`https://tasks.googleapis.com/tasks/v1/lists/${encodeURIComponent(item.google_task_list_id)}/tasks/${encodeURIComponent(item.external_id)}`;const response=await fetch(endpoint,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});if(!response.ok&&response.status!==404){const detail=await response.text();throw new Error(`Google API ${response.status}: ${detail}`);}const {error:deleteError}=await admin.from("commitments").delete().eq("id",item.id).eq("user_id",user.id);if(deleteError)throw deleteError;return json({ok:true,googleDeleted:true});}catch(error){return json({error:error instanceof Error?error.message:String(error)},500);}});
