import { Ionicons } from '@expo/vector-icons';
import { Redirect, Tabs } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppChrome } from '@/components/AppChrome';
import { palette } from '@/components/ui';
import { recordDiagnostic, subscribeDiagnostics } from '@/lib/diagnostics';
import { useFlowStore } from '@/lib/store';
import { useAuth } from '@/providers/AuthProvider';
import { t, useLanguage } from '@/lib/i18n';
function isTodayItem(value:string|undefined,allDay?:boolean){if(!value)return false;const date=new Date(value),now=new Date();if(allDay)return date.getUTCFullYear()===now.getFullYear()&&date.getUTCMonth()===now.getMonth()&&date.getUTCDate()===now.getDate();return date.getFullYear()===now.getFullYear()&&date.getMonth()===now.getMonth()&&date.getDate()===now.getDate();}
export default function TabsLayout(){const{configured,loading,session}=useAuth();const { language } = useLanguage();const commitments=useFlowStore(state=>state.commitments);const insets=useSafeAreaInsets();const[errorCount,setErrorCount]=useState(0);useEffect(()=>subscribeDiagnostics(entries=>setErrorCount(entries.filter(entry=>entry.level==='error').length)),[]);const todayCount=useMemo(()=>commitments.filter(item=>item.status!=='done'&&isTodayItem(item.scheduledAt??item.dueAt,item.allDay)).length,[commitments]);useEffect(()=>{recordDiagnostic('tabs-layout-state',{configured,loading,hasSession:Boolean(session),userId:session?.user.id??null});},[configured,loading,session]);if(loading)return <View style={styles.loading}><ActivityIndicator/></View>;if(configured&&!session){recordDiagnostic('tabs-layout-redirect-login');return <Redirect href="/login"/>;}const bottom=insets.bottom;const tabHeight=66+bottom;return <View style={styles.root}><Tabs initialRouteName="today" screenOptions={{headerShown:false,tabBarActiveTintColor:palette.primary,tabBarStyle:{height:tabHeight,paddingBottom:Math.max(7,bottom+2),paddingTop:6,borderTopWidth:0,elevation:10},tabBarLabelStyle:{fontWeight:'700',fontSize:11}}}><Tabs.Screen name="today" options={{title:t('Oggi',undefined,language),tabBarBadge:todayCount>0?todayCount:undefined,tabBarIcon:({color,size})=><Ionicons name="sparkles" color={color} size={size}/>}}/><Tabs.Screen name="plan" options={{title:t('Lista',undefined,language),tabBarIcon:({color,size})=><Ionicons name="calendar" color={color} size={size}/>}}/><Tabs.Screen name="calendar" options={{title:t('Calendario',undefined,language),tabBarIcon:({color,size})=><Ionicons name="calendar-outline" color={color} size={size}/>}}/><Tabs.Screen name="capture" options={{title:t('Aggiungi',undefined,language),tabBarIcon:({color,size})=><Ionicons name="add-circle" color={color} size={size+10}/>}}/><Tabs.Screen name="me" options={{title:t('Impostazioni',undefined,language),tabBarBadge:errorCount>0?errorCount:undefined,tabBarIcon:({color,size})=><Ionicons name="person" color={color} size={size}/>}}/></Tabs><AppChrome/></View>}
const styles=StyleSheet.create({root:{flex:1},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:palette.bg}});
