import { useEffect, useMemo, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Chip, palette } from '@/components/ui';
import { CommitmentSourceTag } from '@/components/CommitmentSourceTag';
import { ManageSheet } from '@/components/ManageSheet';
import { formatDurationLabel } from '@/lib/itemTiming';
import { getGoogleWorkspaceStatus, type GoogleWorkspaceStatus } from '@/lib/googleWorkspace';
import { useFlowStore } from '@/lib/store';
import type { Commitment } from '@/types';
const DAY_NAMES=['Lun','Mar','Mer','Gio','Ven','Sab','Dom'];const MONTH_NAMES=['gennaio','febbraio','marzo','aprile','maggio','giugno','luglio','agosto','settembre','ottobre','novembre','dicembre'];
function dayKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}function itemDate(item:Commitment){return item.scheduledAt??item.dueAt;}function monthLabel(date:Date){return `${MONTH_NAMES[date.getMonth()]} ${date.getFullYear()}`;}function weekLabel(week:Date[]){const first=monthLabel(week[0]),last=monthLabel(week[6]);return first===last?first:`${first} - ${last}`;}function kindLabel(kind:Commitment['kind']){return kind==='event'?'EVENTO':kind==='task'?'TASK':kind==='reminder'?'REMINDER':'ALTRO';}function tone(kind:Commitment['kind']){return kind==='event'?'primary':kind==='task'?'warning':'success' as const;}function cardStyle(kind:Commitment['kind']){return kind==='event'?styles.event:kind==='task'?styles.task:styles.reminder;}
export default function Calendar(){const commitments=useFlowStore(state=>state.commitments);const[manageId,setManageId]=useState<string|null>(null);const[google,setGoogle]=useState<GoogleWorkspaceStatus|null>(null);useEffect(()=>{void getGoogleWorkspaceStatus().then(setGoogle).catch(()=>setGoogle(null));},[]);const weeks=useMemo(()=>{const now=new Date();const start=new Date(now.getFullYear(),now.getMonth(),now.getDate());start.setDate(start.getDate()-((start.getDay()+6)%7));return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d;});},[]);const grouped=Array.from({length:6},(_,i)=>weeks.slice(i*7,i*7+7));const byDay=useMemo(()=>{const map=new Map<string,Commitment[]>();for(const item of commitments.filter(item=>!item.deletedAt&&item.status!=='done')){const value=itemDate(item);if(!value)continue;const d=new Date(value);const key=item.allDay?`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`:dayKey(d);const list=map.get(key)??[];list.push(item);map.set(key,list);}for(const list of map.values())list.sort((a,b)=>new Date(itemDate(a)??0).getTime()-new Date(itemDate(b)??0).getTime());return map;},[commitments]);const manageItem=manageId?commitments.find(item=>item.id===manageId)??null:null;
return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.wrap}><Text style={styles.eyebrow}>FlowOS</Text><Text style={styles.title}>Calendario</Text><Text style={styles.sub}>Vista per settimane. Tocca qualsiasi attività per aprirla.</Text>{grouped.map((week,index)=><Card key={index} style={styles.weekCard}><Text style={styles.weekTitle}>{weekLabel(week)}</Text>{week.map(date=>{const items=byDay.get(dayKey(date))??[];const today=dayKey(date)===dayKey(new Date());return <View key={date.toISOString()} style={[styles.dayRow,today&&styles.todayRow]}><View style={styles.dayLabel}><Text style={[styles.dayName,today&&styles.todayText]}>{DAY_NAMES[(date.getDay()+6)%7]}</Text><Text style={[styles.dayNumber,today&&styles.todayText]}>{date.getDate()}</Text></View><View style={styles.dayItems}>{items.length?items.slice(0,3).map(item=><Pressable key={item.id} onPress={()=>setManageId(item.id)} style={({pressed})=>[styles.item,cardStyle(item.kind),pressed&&styles.itemPressed]}><View style={styles.itemLine}><Chip tone={tone(item.kind)}>{kindLabel(item.kind)}</Chip><Text numberOfLines={1} style={styles.itemTime}>{item.allDay?'Tutto il giorno':new Date(itemDate(item)!).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</Text></View><Text numberOfLines={1} style={styles.itemTitle}>{item.title}</Text><View style={styles.itemFooter}><Text numberOfLines={1} style={styles.itemMeta}>{formatDurationLabel(item)}{item.location?` · ${item.location}`:''}</Text><CommitmentSourceTag item={item} google={google}/></View></Pressable>):<Text style={styles.emptyDay}>Nessuna attività</Text>}{items.length>3?<Text style={styles.more}>+{items.length-3} altre attività</Text>:null}</View></View>;})}</Card>)}{manageItem?<ManageSheet item={manageItem} onClose={()=>setManageId(null)}/>:null}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},wrap:{padding:16,paddingBottom:110,gap:12},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1.4,color:palette.primary,marginTop:14},title:{fontSize:32,fontWeight:'900',color:palette.ink},sub:{fontSize:14,lineHeight:20,color:palette.muted},weekCard:{padding:12,gap:0},weekTitle:{fontSize:18,lineHeight:23,fontWeight:'900',color:palette.ink,textTransform:'capitalize',marginBottom:5},dayRow:{flexDirection:'row',minHeight:49,borderTopWidth:1,borderTopColor:'#EEF0F5',paddingVertical:5,gap:8},todayRow:{backgroundColor:'#FAF9FF',borderRadius:10},dayLabel:{width:40,alignItems:'center',justifyContent:'flex-start',paddingTop:3},dayName:{fontSize:9,fontWeight:'900',color:palette.muted,textTransform:'uppercase'},dayNumber:{fontSize:18,lineHeight:21,fontWeight:'900',color:palette.ink},todayText:{color:palette.primary},dayItems:{flex:1,minWidth:0,gap:4},item:{borderRadius:9,borderWidth:1,paddingHorizontal:7,paddingVertical:5,minWidth:0},event:{backgroundColor:'#EEF1FE',borderColor:'#C7D0FB'},task:{backgroundColor:'#FFF7E8',borderColor:'#F3DCA8'},reminder:{backgroundColor:'#EAFBF3',borderColor:'#B9EAD4'},itemPressed:{opacity:.8},itemLine:{flexDirection:'row',alignItems:'center',gap:5},itemTime:{fontSize:9,fontWeight:'800',color:palette.muted,flex:1},itemTitle:{fontSize:12,lineHeight:15,fontWeight:'900',color:palette.ink,marginTop:2},itemFooter:{flexDirection:'row',alignItems:'center',gap:5},itemMeta:{fontSize:9,lineHeight:13,color:palette.muted,flex:1},emptyDay:{fontSize:11,color:palette.muted,paddingVertical:7},more:{fontSize:10,fontWeight:'900',color:palette.primary,paddingVertical:2}});
