import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import * as Clipboard from 'expo-clipboard';
import { Button, Card, ScreenShell, palette, showAlert, showConfirm } from '@/components/ui';
import { clearDiagnostics, readDiagnostics, recordDiagnostic, subscribeDiagnostics, type DiagnosticEntry } from '@/lib/diagnostics';
import { deleteAllFlowOSOnlyData } from '@/lib/commitmentsRepository';
import { deleteFlowOSAccount } from '@/lib/account';
import { connectGoogleFromSession, disconnectGoogleWorkspace, getGoogleWorkspaceStatus, isSyncGenuinelyStale, recoverStaleGoogleSyncState, setCalendarSelected, setDefaultCalendar, setDefaultTaskList, friendlyCalendarName, setSyncRange, setTaskListSelected, signInWithGoogle, subscribeToSyncProgress, syncGoogleWorkspace, type GoogleWorkspaceStatus } from '@/lib/googleWorkspace';
import { useFlowStore } from '@/lib/store';
import { useAuth } from '@/providers/AuthProvider';
import * as Application from 'expo-application';

function syncDate(value?:string|null){return value?new Date(value).toLocaleString('it-IT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'mai sincronizzata';}
function logLine(entry:DiagnosticEntry){const time=new Date(entry.at).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit',second:'2-digit'});return `${time} [${entry.level}] ${entry.event}${entry.details?` — ${entry.details}`:''}`;}
function missingAuth(status:GoogleWorkspaceStatus|null,error:string|null){return /google account is not connected|account google non.*collegato/i.test(`${status?.connection?.last_sync_error??''} ${error??''}`);}

export default function Me(){
  const[google,setGoogle]=useState<GoogleWorkspaceStatus|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[progress,setProgress]=useState(0);const[stage,setStage]=useState('');const[logs,setLogs]=useState<DiagnosticEntry[]>([]);const[showLogs,setShowLogs]=useState(true);const[rangeStart,setRangeStart]=useState('');const[rangeEnd,setRangeEnd]=useState('');
  const hydrate=useFlowStore(s=>s.hydrateFromCloud);const{session,signOut}=useAuth();
  async function loadGoogle(repair=true){try{const status=await getGoogleWorkspaceStatus();if(repair&&!busy&&isSyncGenuinelyStale(status.connection)){await recoverStaleGoogleSyncState();setGoogle(await getGoogleWorkspaceStatus());}else setGoogle(status);setError(status.connection?.last_sync_status==='error'?status.connection.last_sync_error??null:null);}catch(e){const message=e instanceof Error?e.message:'Impossibile leggere lo stato Google.';setError(message);recordDiagnostic('google-status-load-failed',{message},'error');}}
  useEffect(()=>{void loadGoogle();const u=subscribeDiagnostics(e=>setLogs([...e].reverse()));return u;},[]);
  useEffect(()=>{if(google?.range){const toInput=(v:string)=>{const[d,m,y]=v.split('/');return `${d}-${m}-${y}`;};setRangeStart(toInput(google.range.labelStart));setRangeEnd(toInput(google.range.labelEnd));}},[google?.range?.labelStart,google?.range?.labelEnd]);
  useEffect(()=>{const u=subscribeToSyncProgress(p=>{setProgress(p.percent);setStage(p.stage);});return u;},[]);
  async function run(action:()=>Promise<unknown>){if(busy)return;setBusy(true);setError(null);try{await action();await loadGoogle(false);}catch(e){const message=e instanceof Error?e.message:'Operazione Google non riuscita.';setError(message);recordDiagnostic('google-operation-failed',{message},'error');showAlert('Google Workspace',message);}finally{setBusy(false);}}
  async function sync(){if(busy)return;setBusy(true);setError(null);setProgress(1);setStage('Avvio della sincronizzazione');try{if(session?.provider_token)await connectGoogleFromSession(session,true);await syncGoogleWorkspace(p=>{setProgress(p.percent);setStage(p.stage);});await hydrate();await loadGoogle(false);}catch(e){const message=e instanceof Error?e.message:'Sincronizzazione non riuscita.';setError(message);recordDiagnostic('sync-ui-failed',{message},'error');showAlert('Sincronizzazione Google',message);await loadGoogle(false);}finally{setBusy(false);setTimeout(()=>{setProgress(0);setStage('');},1500);}}
  async function saveRange(){const iso=(v:string)=>{const[d,m,y]=v.split('-');return d&&m&&y?`${y}-${m}-${d}`:null;};const start=iso(rangeStart),end=iso(rangeEnd);if(!start||!end){showAlert('Google Workspace','Usa il formato GG-MM-AAAA.');return;}await run(async()=>{await setSyncRange(start,end);});}
  async function wipe(){if(busy)return;const ok=await showConfirm('Eliminare ogni attività su FlowOS?','Le attività vengono eliminate solo da FlowOS. Google Calendar e Google Tasks non vengono modificati.','Elimina tutto');if(!ok)return;setBusy(true);try{await deleteAllFlowOSOnlyData();await hydrate();showAlert('FlowOS','Attività eliminate da FlowOS.');}catch(e){showAlert('FlowOS',e instanceof Error?e.message:'Eliminazione non riuscita.');}finally{setBusy(false);}}
  async function deleteAccount(){if(busy)return;const ok=await showConfirm('Eliminare definitivamente l’account?','L’operazione è irreversibile.','Elimina definitivamente');if(!ok)return;setBusy(true);try{await deleteFlowOSAccount();router.replace('/login');}catch(e){showAlert('FlowOS',e instanceof Error?e.message:'Eliminazione account non riuscita.');}finally{setBusy(false);}}
  async function logout(){if(busy)return;try{await signOut();router.replace('/login');}catch(e){showAlert('FlowOS',e instanceof Error?e.message:'Logout non riuscito.');}}
  async function copyLogs(){const text=`FlowOS ${Application.nativeApplicationVersion??'unknown'} · versionCode ${Application.nativeBuildVersion??'unknown'}\n${readDiagnostics().map(logLine).join('\n')}`;if(!readDiagnostics().length)return showAlert('Logger','Nessun log disponibile.');await Clipboard.setStringAsync(text);showAlert('Logger','Log copiato.');}
  const connected=Boolean(google?.connection&&google.connection.last_sync_status!=='disconnected'&&!missingAuth(google,error));
  return <ScreenShell title="Impostazioni">
    <Card><Text style={styles.label}>Google Workspace</Text><Text style={styles.meta}>Intervallo importazione: {google?.range?`${google.range.labelStart} → ${google.range.labelEnd}`:'caricamento…'}</Text><View style={styles.inline}><TextInput value={rangeStart} onChangeText={setRangeStart} placeholder="GG-MM-AAAA" style={styles.input}/><TextInput value={rangeEnd} onChangeText={setRangeEnd} placeholder="GG-MM-AAAA" style={styles.input}/><Button secondary label="Salva" onPress={()=>{void saveRange();}}/></View>{connected?<><Text style={styles.item}>{friendlyCalendarName(google?.connection?.google_email??'Account Google',google?.connection?.google_email)}</Text><Text style={styles.meta}>Stato: {google?.connection?.last_sync_status} · Ultima: {syncDate(google?.connection?.last_sync_at)}</Text>{error?<Text style={styles.error}>{error}</Text>:null}{progress>0?<><View style={styles.progressHeader}><Text style={styles.meta}>{stage}</Text><Text style={styles.meta}>{progress}%</Text></View><View style={styles.track}><View style={[styles.fill,{width:`${progress}%`}]}/></View></>:null}<View style={styles.actions}><Button label={busy?'Sincronizzazione…':'Sincronizza ora'} onPress={()=>{void sync();}} disabled={busy}/><Button secondary label="Scollega Google" onPress={()=>{void run(disconnectGoogleWorkspace);}} disabled={busy}/></View></>:<><Text style={styles.meta}>{missingAuth(google,error)?'L’autorizzazione Google deve essere ripristinata.':'Google non è collegato.'}</Text><Button label="Collega Google" onPress={()=>{void run(signInWithGoogle);}} disabled={busy}/></>}</Card>
    {connected?<><Card><Text style={styles.label}>Calendari sincronizzati</Text>{google?.calendars.map(c=><View key={c.id} style={styles.resource}><View style={styles.resourceText}><Text style={styles.item}>{friendlyCalendarName(c.summary,google?.connection?.google_email)}</Text><Text style={styles.meta}>{c.access_role}{c.is_default?' · predefinito':''}</Text></View><Switch value={c.selected} onValueChange={v=>{void run(()=>setCalendarSelected(c.id,v));}}/><Pressable disabled={!c.selected||!['owner','writer'].includes(c.access_role)||c.is_default} onPress={()=>{void run(()=>setDefaultCalendar(c.id));}}><Text style={styles.link}>{c.is_default?'Default':'Default'}</Text></Pressable></View>)}</Card><Card><Text style={styles.label}>Liste Google Tasks</Text>{google?.taskLists.map(l=><View key={l.id} style={styles.resource}><View style={styles.resourceText}><Text style={styles.item}>{l.title}</Text><Text style={styles.meta}>{l.is_default?'Predefinita':'Lista attività'}</Text></View><Switch value={l.selected} onValueChange={v=>{void run(()=>setTaskListSelected(l.id,v));}}/><Pressable disabled={!l.selected||l.is_default} onPress={()=>{void run(()=>setDefaultTaskList(l.id));}}><Text style={styles.link}>{l.is_default?'Default':'Default'}</Text></Pressable></View>)}</Card></>:null}
    <Card><Text style={styles.label}>Notifiche</Text><Text style={styles.meta}>Promemoria e riepilogo giornaliero.</Text><Button secondary label="Apri impostazioni notifiche" onPress={()=>router.push('/notifications-settings')}/></Card>
    <Card><Text style={styles.label}>Dati FlowOS</Text><Text style={styles.meta}>Puoi cancellare le attività locali in qualsiasi momento, indipendentemente dal collegamento Google.</Text><Pressable onPress={()=>{void wipe();}} style={styles.dangerButton}><Text style={styles.danger}>Elimina ogni attività su FlowOS senza alcun impatto su Google</Text></Pressable></Card>
    <Card><View style={styles.diagnosticHeader}><View><Text style={styles.label}>Diagnostica</Text><Text style={styles.meta}>FlowOS {Application.nativeApplicationVersion??'unknown'} · versionCode {Application.nativeBuildVersion??'unknown'} · {logs.length} eventi</Text></View><Button secondary label="Mostra/nascondi log" onPress={()=>setShowLogs(v=>!v)}/></View><View style={styles.actions}><Button secondary label="Copia log" onPress={()=>{void copyLogs();}}/><Button secondary label="Cancella log" onPress={()=>{clearDiagnostics();setLogs([]);}}/></View>{showLogs?<View style={styles.logBox}><Text selectable style={styles.logText}>{`FlowOS ${Application.nativeApplicationVersion??'unknown'} · versionCode ${Application.nativeBuildVersion??'unknown'}\n${logs.length?logs.map(logLine).join('\n'):'Nessun evento registrato.'}`}</Text></View>:null}</Card>
    <Card><Button secondary label="Esci da FlowOS" onPress={()=>{void logout();}} disabled={busy}/><Pressable onPress={()=>{void deleteAccount();}} style={styles.delete}><Text style={styles.danger}>Elimina definitivamente l’account</Text></Pressable></Card>
  </ScreenShell>;
}
const styles=StyleSheet.create({label:{fontSize:17,fontWeight:'900',color:palette.ink,marginBottom:6},meta:{fontSize:12,lineHeight:17,color:palette.muted},item:{fontSize:14,fontWeight:'800',color:palette.ink},inline:{flexDirection:'row',alignItems:'center',gap:6,marginTop:8},input:{flex:1,minWidth:0,borderWidth:1,borderColor:palette.border,borderRadius:10,paddingHorizontal:10,paddingVertical:9,fontSize:12,color:palette.ink},actions:{flexDirection:'row',gap:8,flexWrap:'wrap',marginTop:10},error:{fontSize:12,color:palette.warning,marginTop:7},progressHeader:{flexDirection:'row',justifyContent:'space-between',marginTop:10},track:{height:7,borderRadius:4,backgroundColor:'#E5E7EE',overflow:'hidden',marginTop:5},fill:{height:7,backgroundColor:palette.primary},resource:{flexDirection:'row',alignItems:'center',gap:8,paddingVertical:8,borderTopWidth:1,borderTopColor:palette.border},resourceText:{flex:1},link:{fontSize:11,fontWeight:'800',color:palette.primary},dangerButton:{marginTop:10,padding:12,borderRadius:12,backgroundColor:'#FFF0F0'},danger:{fontSize:12,fontWeight:'900',color:'#A12626'},delete:{marginTop:12,padding:8,alignItems:'center'},diagnosticHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},logBox:{marginTop:10,maxHeight:420,borderRadius:12,backgroundColor:'#111827',padding:10},logText:{fontFamily:'monospace',fontSize:10,lineHeight:15,color:'#F3F4F6'}});