name: Deploy web preview

on:
  push:
    branches: ['main']

jobs:
  deploy_web:
    name: Deploy web (preview)
    environment: preview
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Deploy to EAS Hosting
        run: npx eas-cli@latest deploy --non-interactive --dev-domain flowos-alex16nardi --environment preview --alias flowos-private
